### ISSUE TITLE
E2E: You buy a domain on top of a subdomain

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#587] opened 2023-12-18 16:32 UTC
https://testnet.starkscan.co/tx/0x5ea1c5275d617f8c2f7c6b9b585e8ee68d5c6f2d774b2ecf9275408bf50c5d8
550396886414 had the subdomain avimak.motty.fricoben.stark

**Comment by Th0rgal** [comment] 2023-12-20 11:42
<img width="580" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/cb362801-4daa-42c0-850b-b5ed126c419b">
Cannot reproduce on a domain, I will retry on a subdomain

**Comment by Th0rgal** [comment] 2023-12-20 12:05
Should be fixed after an update of the contract

**Closed as completed** 2023-12-22 14:14 UTC
Labels: 🚨 Important bug, 🔥 Ready for review
